name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Building Docker Image For Testing
      run: docker build -f ./client/Dockerfile.dev -t silvarthur/react-test ./client
      
    - name: Running tests
      run: docker run -e CI=true silvarthur/react-test npm test

    - name: Building Images for Sendig to Docker Hub
      run: |
      docker build -t silvarthur/multi-client ./client
      docker build -t silvarthur/multi-nginx ./nginx
      docker build -t silvarthur/multi-server ./server
      docker build -t silvarthur/multi-worker ./worker