name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Building Docker Image For Testing
      run: docker build -f ./client/Dockerfile.dev -t silvarthur/react-test ./client
      
    - name: Running tests
      run: docker run -e CI=true silvarthur/react-test npm test

    - name: Building Client Image for Sendig to Docker Hub
      run: docker build -t silvarthur/multi-client ./client

    - name: Building Nginx Image for Sendig to Docker Hub
      run: docker build -t silvarthur/multi-nginx ./nginx

    - name: Building Server Image for Sendig to Docker Hub  
      run: docker build -t silvarthur/multi-server ./server

    - name: Building Worker Image for Sendig to Docker Hub
      run: docker build -t silvarthur/multi-worker ./worker